---
abstract: 'Run Pod::POM::Web as a PSGI application'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-POM-Web-PSGI
requires:
  CGI::Compile: 0.15
  CGI::Emulate::PSGI: 0.12
  Plack: 0.9979
  Pod::POM::Web: 1.17
resources:
  homepage: http://github.com/dolmen/p5-Pod-POM-Web-PSGI
  repository: http://github.com/dolmen/p5-Pod-POM-Web-PSGI
version: 0.001
